#!/bin/bash

is_git_repo() {
    git rev-parse --show-toplevel > /dev/null 2>&1
    result=$?
    if test $result != 0; then
        >&2 echo 'Not a git repo!'
        exit $result
  fi
}

is_git_repo

ALL=0

while [[ $# -ge 1 ]]
do
key="$1"

case $key in
    -c| --commits)
    COMMITS="$2"
    if [ -z "${COMMITS}" ]; then COMMITS="5"; fi;
    shift
    ;;
    -a| --all)
    ALL=1
    shift
    ;;
    *)
    # unknown option
    ;;
esac
shift
done

die () {
    echo >&2 `basename $0`: $*
    exit 1
}

tmpfile=$(mktemp gitblah-XXXX)
[ -f "$tmpfile" ] || die "could not get tmpfile=[$tmpfile]"
trap "rm -f $tmpfile" EXIT


datefmt=%cI
if [ "`git log -n1  --pretty=format:"$datefmt"`" == "$datefmt" ];
then
    datefmt=%ci
fi

if [ "${ALL}" -eq 1 ];
then
    git log --pretty=format:"$datefmt | %H | %s" > $tmpfile;
else
    if [ -n "${COMMITS+set}" ];
    then git log -n $COMMITS --pretty=format:"$datefmt | %H | %s" > $tmpfile;
    else git log -n 5 --pretty=format:"$datefmt | %H | %s" > $tmpfile;
    fi
fi

${VISUAL:-${EDITOR:-vi}} $tmpfile


ENVFILTER=""
while read commit; do
    IFS="|" read date hash message <<< "$commit"
    shopt -s nocasematch
    if [[ "$date" == 'now' ]]; then
        date=$(date +%Y-%m-%dT%H:%M:%S%z);
    fi
    shopt -u nocasematch
    if [ "$datefmt" == "%cI" ]
    then
        DATE_NO_SPACE="$(echo "${date}" | tr -d '[[:space:]]')"
    else
        DATE_NO_SPACE="$(echo "${date}")"
    fi
    COMMIT_ENV=$(cat <<-END
        if [ \$GIT_COMMIT = $hash ];
        then
            export GIT_AUTHOR_DATE="$DATE_NO_SPACE"
            export GIT_COMMITTER_DATE="$DATE_NO_SPACE";
        fi;
	END
    )
    ENVFILTER="$ENVFILTER$COMMIT_ENV"
done < $tmpfile

if [ "${ALL}" -eq 1 ];
then
    git filter-branch -f --env-filter "$ENVFILTER" -- --all >/dev/null
else
    git filter-branch -f --env-filter "$ENVFILTER" HEAD~$COMMITS..HEAD >/dev/null
fi

if [ $? = 0 ] ; then
    echo "Git commit dates updated. Run 'git push -f BRANCH_NAME' to push your changes."
else
    echo "Git redate failed. Please make sure you run this on a clean working directory."
fi
